### ISSUE TITLE
test interaction of makeskin and MPFB

### ISSUE THREAD

**Issue by black-punkduck** [makehumancommunity/community-plugins-makeskin#5]
assignAsNodesMaterialForObj()  number of arguments changed (uses scene, object and a load flag instead of object, because of scene all parameters attached as custom properties to scene are no longer needed)

I simply did not know that MPFB also uses the functionality :(

... I will create an own branch of MPFB and hope I get the thing working soon ... 

(I took an issue to communicate maybe because I have no idea to answer another way), hope it is okay

**Comment by black-punkduck** [comment]
I changed code for MPFB a tiny bit, on my box it works ... I also tried a merge request for punkduck-devel but it looks like when I press the button it is already merged. So since you want them fitting all together best do all three merges then. I don't want to produce chaos ;)

**Comment by joepal1976** [comment]
Ok, things work for me too now, when I have punkduck_devel checked out in all plugins locally. 

So I'll merge everything now.
